# Generated by Django 5.1.4 on 2025-04-21 15:14

import django.db.models.deletion
import django.utils.timezone
import multimedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=multimedia.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('id', models.UUIDField(default=multimedia.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('dj_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('cartId', models.UUIDField(default=multimedia.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(default='https://images.unsplash.com/photo-1579713899713-bcd3efe713aa?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', upload_to='genre/')),
            ],
            options={
                'db_table': 'cartegories',
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('vidId', models.UUIDField(default=multimedia.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='videoImage/')),
                ('popular', models.BooleanField(default=False)),
                ('season', models.CharField(default='season 1', max_length=150)),
                ('purchase_times', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to='videos/')),
                ('likes', models.IntegerField(default=0)),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='multimedia.category', to_field='category_name')),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.dj', to_field='dj_name', verbose_name='video Type')),
                ('genre', models.ForeignKey(default='Action', on_delete=django.db.models.deletion.CASCADE, related_name='video_details', to='multimedia.genre', to_field='title')),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=multimedia.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(default='anonymous', max_length=150)),
                ('rate', models.IntegerField()),
                ('comment', models.TextField()),
                ('video_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='multimedia.videoupload')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalVideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='additional_videos/')),
                ('video_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='multimedia.videoupload')),
            ],
            options={
                'db_table': 'additional_video_files',
            },
        ),
    ]
