# Generated by Django 5.1.4 on 2025-04-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.dj', to_field='dj_name', verbose_name='video_details'),
        ),
    ]
