# Generated by Django 5.1.4 on 2025-04-25 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_alter_videoupload_dj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_details', to='multimedia.dj', to_field='dj_name'),
        ),
    ]
