# Generated by Django 5.1.4 on 2025-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_alter_videoupload_dj'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
