# Generated by Django 5.1.4 on 2025-04-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_videoupload_is_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoupload',
            old_name='is_top',
            new_name='suggest',
        ),
    ]
