# Generated by Django 5.1.4 on 2025-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(default=1886253, max_length=100, unique=True),
        ),
    ]
